# Generated by Django 5.0.1 on 2024-01-13 00:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-date_created"]},
        ),
    ]
